config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :groups, only: [:index, :new, :create] do
    resources :investments, only: [:index, :new, :create, :destroy]
  end

  root to: 'splash#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Group, user_id: user.id
    can :manage, Investment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :investments
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_many :groups, dependent: :destroy
  has_many :investments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :check_page
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def check_page
    session[:current_page] = nil
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:investments).all
    session[:current_page] = 'Groups'
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_investment, only: %i[show edit update destroy]

  # GET /investments or /investments.json
  def index
    @investments = Investment.where(group_id: params[:group_id])
    @group_name = Group.find(params[:group_id])
    session[:current_page] = 'Investments'
  end

  # GET /investments/1 or /investments/1.json
  def show; end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit; end

  # POST /investments or /investments.json
  def create
    params[:investment][:group_id].each do |g|
      unless g.empty?
        @investment = Investment.new(investment_params.merge(user_id: current_user.id, group_id: g))
        @investment.save
      end
    end
    redirect_to group_investments_path
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to investment_url(@investment), notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to group_investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_investment
    @investment = Investment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def investment_params
    params.require(:investment).permit(:name, :amount)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    groups_path
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    session[:current_page] = 'Splash'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_investments_helper.rb
module GroupInvestmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, class: "input is-medium", placeholder: "Group or Company name" %>
  </div>

  <div class="field">
    <%= form.text_field :icon, class: "input is-medium", placeholder: "URL address for icon" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Group", class: "button is-success is-large is-fullwidth" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<article id="<%= dom_id group %>" class="media">
  <div class="media-left">
    <figure class="image is-96x96">
      <img src="<%= group.icon %>" alt="logo">
    </figure>
  </div>
  <div class="media-content">
    <div class="content">
      <h2 class="subtitle is-3">
        <%= group.name %>
      </h2>
    </div>
  </div>
  <div class="subtitle is-4">
    Invested: $ <%= (group.investments.collect { |i| i.amount }).sum.round(2) %>
  </div>
</article>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="groups">
  <% @groups.each do |group| %>
    <%= link_to group_investments_path(group), method: :get, class: "box" do %>
      <%= render group %>
    <% end %>
  <% end %>
</div>
<div class="navbar is-fixed-bottom bottom">
  <%= link_to "New Group", new_group_path, {method: :get, class: "button is-large is-outlined is-fullwidth bottom-btn"} %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>
<br>
<div class="navbar is-fixed-bottom bottom">
  <%= link_to "Back to Groups", groups_path, {method: :get, class: "button is-large is-outlined is-fullwidth bottom-btn"} %>
</div>

app/views/investments/_form.html.erb
<%= form_with(model: [:group, investment]) do |form| %>
  <% if investment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
        <% investment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, class: "input is-medium", placeholder: "Type of investment" %>
  </div>

  <div class="field">
    <p class="control has-icons-left">
    <%= form.text_field :amount, class: "input is-medium", placeholder: "Money invested" %>
      <span class="icon is-left">
        $
      </span>
    </p>
  </div>

  <div class="field">
    <div class="select is-multiple is-large is-fullwidth">
      <%= form.collection_select(:group_id, Group.all, :id, :name, {}, {:multiple => true}) %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Create Investment", class: "button is-success is-large is-fullwidth" %>
  </div>
<% end %>

app/views/investments/_investment.html.erb
<div class="column">
  <h3 class="subtitle is-4">
    <strong>Type: </strong>
    <%= investment.name %>
  </h3>
</div>

<div class="column">
  <h3 class="subtitle is-4">
    <strong>Amount: </strong>
    $ <%= investment.amount %>
  </h3>
</div>

app/views/investments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title is-1">Investments on <%= @group_name.name %></h1>

<div id="investments">
  <% @investments.each do |investment| %>
    <div class="box">
      <div class="columns">
        <%= render investment %>
        <div class="column is-one-fifth">
          <%= button_to "Delete", group_investment_path(id: investment.id), {method: :delete, class: "button is-danger is-medium"} %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="navbar is-fixed-bottom bottom">
  <%= link_to "New Investment", new_group_investment_path, {method: :get, class: "button is-large is-outlined is-fullwidth bottom-btn"} %>
</div>

app/views/investments/new.html.erb
<%= render "form", investment: @investment %>
<br>
<div class="navbar is-fixed-bottom bottom">
  <%= link_to "Back to Investments", group_investments_path(params['group_id']), {method: :get, class: "button is-large is-outlined is-fullwidth bottom-btn"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= javascript_importmap_tags %>
  </head>
  <body class="has-navbar-fixed-top has-navbar-fixed-bottom">
    <%= render "shared/nav" %>
    <br><br><br>
    <div class="has-background-color container is-max-widescreen">
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar is-fixed-top nav-bg-color" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div>
      <% if session[:current_page] == 'Groups' || session[:current_page] == 'Splash' %>
        <a role="button" class="navbar-burger is-text-white" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <svg style="width:48px;height:48px" viewBox="0 0 24 24">
            <path fill="white" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z" />
          </svg>
        </a>
      <% else %>
        <%= link_to :back do %>
          <svg style="width:48px;height:48px" viewBox="0 0 24 24">
            <path fill="white" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" />
          </svg>
        <% end %>
      <% end %>
    </div>
    <% if session[:current_page].nil? || session[:current_page] == 'Splash' %>
      <h1 class="navbar-burger breadcrumb subtitle is-4" style="color:white">Budget App</h1>
    <% else %>
      <p class="navbar-burger breadcrumb subtitle is-4" style="color:white"><%="#{session[:current_page]}" %></p>
    <% end %>
    <a role="button" class="navbar-burger" aria-label="search" aria-expanded="false">
      <svg style="width:48px;height:48px" viewBox="0 0 24 24">
        <path fill="white" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" />
      </svg>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start title">
      <% if current_page?(groups_path) %>
        <svg style="width:64px;height:64px" viewBox="0 0 24 24">
          <path fill="white" d="M12 5.69L17 10.19V18H15V12H9V18H7V10.19L12 5.69M12 3L2 12H5V20H11V14H13V20H19V12H22L12 3Z" />
        </svg>
      <% else %>
        <%= link_to :back do %>
          <svg style="width:64px;height:64px" viewBox="0 0 24 24">
            <path fill="white" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" />
          </svg>
        <% end %>
      <% end %>
      <%= link_to "Groups", groups_path, {class: "navbar-item gray"} %>
      <a class="navbar-item gray">Budget</a>
      <a class="navbar-item gray">Income</a>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <% if user_signed_in? %>
            <p class="control">
              <h2 class="title gray">
                <%= current_user.name %>
              </h2>
            </p>
            <p class="control">
              <%= button_to 'Logout', destroy_user_session_path, {method: :delete, class: "button is-large is-danger"} %>
            </p>
          <% else %>
            <p class="control">
              <%= button_to 'Log in', new_user_session_path, {method: :get, class: "button is-large is-info"} %>
            </p>
            <p class="control">
              <%= button_to 'Sign up', new_user_registration_path, {method: :get, class: "button is-large"} %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/splash/index.html.erb
<div class="container">
  <br><br>
  <div class="is-flex is-flex-grow-1 is-justify-content-center is-align-items-center pb-6">
    <p class="content title is-1">
      Investment<br>
      Budget<br>
      Application
    </h1>
  </div>
  <br><br><br>
	<div class="is-flex flex-direction-column size-is buttons px-5">
		<%= link_to "LOG IN", new_user_session_url, class: "button is-large is-fullwidth is-info" %>
		<%= link_to "SIGN UP", new_user_registration_url, class: "button is-large is-fullwidth" %>
	</div>
</div>